### ISSUE TITLE
Mixin Conflict warning on injection

### ISSUE THREAD

**Issue by itsdinkd** [someaddons/cursery#4]
modloader 39.0.59, latest cursery curseforge release, 1.18.1

```java
[26Jan2022 14:27:22.507] [Render thread/WARN] [mixin/]: Mixin apply failed cursery.mixins.json:EnchantmentHelperMixin -> net.minecraft.world.item.enchantment.EnchantmentHelper: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/item/enchantment/EnchantmentHelper::onGetTableEnchants with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [ -> redirect$zgi000$onGetTableEnchants(Lnet/minecraft/world/item/enchantment/Enchantment;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/item/enchantment/EnchantmentHelper::onGetTableEnchants with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [ -> redirect$zgi000$onGetTableEnchants(Lnet/minecraft/world/item/enchantment/Enchantment;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.0.jar:9.1.0+9.1.0+main.6690ee51]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.item.EnchantedBookItem.m_41153_(EnchantedBookItem.java:54) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at net.minecraft.world.item.EnchantedBookItem.m_41161_(EnchantedBookItem.java:78) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at net.minecraft.world.item.EnchantedBookItem.m_6787_(EnchantedBookItem.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at net.minecraft.client.Minecraft.m_91271_(Minecraft.java:710) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:504) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.1-20211210.034407-srg.jar%23373!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by someaddons** [comment]
fixed in 2.8

**Comment by Maypul** [comment]
@someaddons seems the issue is still happening in 2.9 Forge (I do not see 3.0 on curseforge, only for Fabric):
[20:08:38] [Server thread/WARN] [mixin/]: Mixin apply failed cursery.mixins.json:EnchantmentHelperMixin -> net.minecraft.world.item.enchantment.EnchantmentHelper: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/item/enchantment/EnchantmentHelper::onGetTableEnchants with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44909_(Ljava/util/Random;Lnet/minecraft/world/item/ItemStack;IZ)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [ -> redirect$zcl000$onGetTableEnchants(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/item/enchantment/EnchantmentHelper::onGetTableEnchants with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44909_(Ljava/util/Random;Lnet/minecraft/world/item/ItemStack;IZ)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [ -> redirect$zcl000$onGetTableEnchants(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar%235!/:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.storage.loot.functions.ApplyBonusCount.m_7372_(ApplyBonusCount.java:169) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:31) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemFunctions.m_80765_(LootItemFunctions.java:57) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:73) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:95) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:83) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:88) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour.m_7381_(BlockBehaviour.java:247) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:693) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.block.Block.m_49869_(Block.java:255) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.block.Block.m_49892_(Block.java:284) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.WaterFluid.m_7456_(WaterFluid.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:241) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:146) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.FlowingFluid.m_76010_(FlowingFluid.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:410) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:76) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:478) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.m_212887_(ChunkMap.java:692) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.server.level.ChunkMap.m_212877_(ChunkMap.java:691) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:532) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:540) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
